# Generated by Django 4.0 on 2021-12-21 04:58

from django.db import migrations, models
import django.db.models.deletion
import pharmacy_detail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
        ('town', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/default.jpg', upload_to=pharmacy_detail.models.upload_to, verbose_name='Image')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.provincemodel')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.townmodel')),
            ],
        ),
    ]
