# Generated by Django 4.0 on 2021-12-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_farmer_customuser_is_pharmacy_and_more'),
        ('pharmacy_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydetailmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
            preserve_default=False,
        ),
    ]
