# Generated by Django 4.0 on 2021-12-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.provincemodel')),
            ],
        ),
    ]
