# Generated by Django 4.0 on 2021-12-16 21:01

from django.db import migrations, models
import drug.models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_drugmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmodel',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=drug.models.upload_to, verbose_name='Image'),
        ),
    ]
