# Generated by Django 4.0 on 2021-12-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_drugmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
