# Generated by Django 4.0 on 2021-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_drugmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='drugmodel',
            name='price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
