# Generated by Django 4.0 on 2021-12-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_farmer_customuser_is_pharmacy_and_more'),
        ('order', '0002_alter_ordermodel_cancelleddate_and_more'),
        ('drug', '0004_drugmodel_description'),
        ('order_drug', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDrug',
            new_name='OrderDrugModel',
        ),
    ]
