# Generated by Django 4.0 on 2021-12-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
        ('user', '0002_customuser_is_farmer_customuser_is_pharmacy_and_more'),
        ('town', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=255)),
                ('alternateNumber', models.CharField(max_length=255)),
                ('selected', models.BooleanField(default=False)),
                ('compound', models.CharField(max_length=255)),
                ('buldingNumber', models.CharField(max_length=255)),
                ('landMark', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.provincemodel')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.townmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
    ]
