# Generated by Django 4.0 on 2021-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='alternateNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='buldingNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
