# Generated by Django 4.0 on 2021-12-31 06:00

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_farmer_customuser_is_pharmacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to=user.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
    ]
