# Generated by Django 4.0 on 2021-12-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_first_name_customuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
    ]
