# Generated by Django 4.0 on 2021-12-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasemodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
