# Generated by Django 4.0 on 2021-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='cancelledDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='deliveredDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='deliveryPrice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='packedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='transportedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
