# Generated by Django 4.0 on 2021-12-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordermodel_cancelleddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='cancelledDate',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='deliveredDate',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='packedDate',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='transportedDate',
        ),
    ]
